### ISSUE TITLE
프로젝트관련 질문

### ISSUE THREAD

**Issue by softCastella** [DDM-JS-BASIC/WebDevLecture#4]
안녕하세요 선생님!
과제 프로젝트 관련 질문이 있습니다.
저는 채팅앱으로 잘라(?) 주셨는데 막상 만들기 위해 아이디에이션 중 의문이 생겼습니다.
채팅앱은 2명이 채팅을 하고 친구추가 등도 이루어져야 하는데 최종 구현테스트때 이런 부분을 어떻게 보여져야 하는지?? 모르겠습니다.
두명을 제가 다 반응이 있게 작동시켜야하는지 아니면 누군가가 함께 참가를 해줘야하는지? 모르겠습니다.

**Comment by kakadais** [comment]
이번 프로젝트는 기술 체득화에 목표가 있는 만큼 구성은 자유입니다-
제가 단순 채팅앱으로 제안한 이유는 덩어리가 너무 커서이고,
어떠한 방향성을 가질지는 역시 자유입니다.

제 생각에는,
로그인이나 그룹 채팅등은 구성이 복잡하기에 무리가 있을 것 같고,
한 화면에서 스스로 닉네임을 정해서 채팅에 참여하는 방식이 어떨까 하네요.

즉, 페이지에 진입하면 스스로 자신의 닉네임을 정하도록 하고 각 채팅 메시지마다 해당 닉네임을 표현 해 주면 각 채팅 메시지가 구분이 가겠네요-

**Comment by softCastella** [comment]
> 이번 프로젝트는 기술 체득화에 목표가 있는 만큼 구성은 자유입니다-
> 제가 단순 채팅앱으로 제안한 이유는 덩어리가 너무 커서이고,
> 어떠한 방향성을 가질지는 역시 자유입니다.
> 
> 제 생각에는,
> 로그인이나 그룹 채팅등은 구성이 복잡하기에 무리가 있을 것 같고,
> 한 화면에서 스스로 닉네임을 정해서 채팅에 참여하는 방식이 어떨까 하네요.
> 
> 즉, 페이지에 진입하면 스스로 자신의 닉네임을 정하도록 하고 각 채팅 메시지마다 해당 닉네임을 표현 해 주면 각 채팅 메시지가 구분이 가겠네요-

넵 감사합니다 ~
