### ISSUE TITLE
전달드릴 사항이 있습니다.

### ISSUE THREAD

**Issue by softCastella** [DDM-JS-BASIC/WebDevLecture#5]
안녕하세요 진정원 선생님~
최진영입니다
잘 지내시고 계신지 궁금하네요 :)

전달 드릴 사항이 있어 연락 드렸습니다.
실은 제가 갑자기 수강 중단을 하게 되어 연락 드렸습니다.

제가 이번 자바스크립트과정 이전에 5월쯤 신청했던 취업 연계 웹 기획 과정이 있었는데 그게 당시 모집 인원 부족으로 언제 열릴지 불투명한 상황이었습니다.
담당자분도 그렇게 말씀을 하셨었고 설마 여름에 바로 열릴 거라고는 예상을 못해서 여름 동안 개발 지식을 늘리려고 이 코스에 들어왔는데..

저번 주에 갑자기 연락이 와서 이번 주 중으로 면접까지 봐야 한다고 해서 고민하다 면접을 보고 통과한 상태입니다.
말씀은 못드렸지만 가정 형편이 좋지 못해 취업이 엄청 급한 상황이다 보니 제 교육 이력으로 빠르게 취업이 될 수 있는 것이 기획 쪽일 것 같아 급히 결정을 내리게 되었습니다. 

이번 기획 과정이 아니었다면 동부에서 선생님을 또 뵙고 싶었는데 무척이나 아쉽습니다. 또 기회가 된다면 꼭 선생님 수업을 듣고 싶네요.

20일 기획 과정이 개강이라 17일이나 19일 중으로 수강 중단 신청을 할 듯 합니다. 
그래서 추후 관련해 혹시 제가 수강 중단을 하면 현재 깃허브 팀에서 나가야 할지 기존 토이 프로젝트 과제 관련 질문을 올릴 수 없을지 여쭙고 싶습니다.

**Comment by kakadais** [comment]
아 그러셨군요-
좋은 기회가 생기셨다니 축하할 만한 일인 것 같습니다- ㅎ

팀 관련해서는 크기 신경쓰지 않으셔도 됩니다-
모쪼록 학습을 이어가셔서 좋은 결과가 있었으면 좋겠습니다~
